YLW 3119 -  Create book and library classes
davidgreenland/TheEnchantedLibrary pull request #1
Opened 2024-10-02 14:19 UTC by davidgreenland

#### What
Creates a Book and Library class

#### Why
To define the properties of a book an to be able to able to add them to a Library catalogue.

#### How
- Created a book class with Author, Title and Spell properties
- Added a static field that keeps track of number of instances of Book class to use as an ID property.
- Printed some test Catalogues to the console

2024-10-03 08:34 UTC, SiddiqueAbdullah requested changes

2024-10-03 08:34 UTC, SiddiqueAbdullah commented on TheEnchantedLibrary/Models/Book.cs
> +    public static int CountOfBooks { get; private set; }
no

2024-10-03 09:11 UTC, SiddiqueAbdullah commented on TheEnchantedLibrary/Models/Library.cs
> +    public ICollection<Book> Catalogue { get; private set; } = [];
no property

2024-10-03 09:26 UTC, davidgreenland commented on TheEnchantedLibrary/Models/Book.cs
> +    public static int CountOfBooks { get; private set; }
removed

2024-10-03 10:50 UTC, davidgreenland commented on TheEnchantedLibrary/Models/Library.cs
> +    public ICollection<Book> Catalogue { get; private set; } = [];
done

2024-10-04 13:31 UTC, SiddiqueAbdullah approved these changes

2024-10-06 18:29 UTC, merged